"""
Django settings for absharProject project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_o*sce-7v=squt58jj0$l=ezgw^!ek$_%8c2##qd^o&7n@4v0h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django_select2',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # main_app
    'channels',
    'user_app',
    'admin_panel',
    'middleAdmin_panel',
    'notifications',
    'admin_payment_app',
    'home',
    'polls_app',
    'mobileApp',

    # 'jalali_date',

    'polls',
    'payment_app',
    'reports',
    #
    # # other_app
    'django_render_partial',
    'sweetify',
    'jalali_date',

    'ckeditor',
    'ckeditor_uploader',  # enables file & image uploads
    'azbankgateways',
    'django_celery_beat',
    # 'django_select2',

]
# تنظیمات REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],

    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 20,

    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],

    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),

    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,

    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),

    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
# AZ_IRANIAN_BANK_GATEWAYS = {
#    'GATEWAYS': {
#        'MELLAT': {
#            'TERMINAL_CODE': '8807710',
#            'USERNAME': '8807710',
#            'PASSWORD': '64728741',
#        },
#    },
#    'DEFAULT': 'MELLAT',
#    'CURRENCY': 'IRR', # اختیاری
#    'TRACKING_CODE_QUERY_PARAM': 'tc', # اختیاری
#    'TRACKING_CODE_LENGTH': 16, # اختیاری
#    'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader', # اختیاری
#    'BANK_PRIORITIES': [
#    ], # اختیاری
# }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'home.middleware.SubdomainMiddleware',
]
AUTH_USER_MODEL = 'user_app.User'

ROOT_URLCONF = 'absharProject.urls'

LOGIN_URL_ADMIN = '/admin-panel/login-admin/'
LOGIN_URL_MIDDLE_ADMIN = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {

            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'absharProject.context_processors.current_house',
                'absharProject.context_processors.user_header_notifications',
                'absharProject.context_processors.current_middle_house',
                'absharProject.context_processors.middle_header_notifications',
                'absharProject.context_processors.admin_header_notifications',
                'absharProject.context_processors.impersonation_banner',
                'absharProject.context_processors.user_unit_context',

            ],
        },
    },
]

# WSGI_APPLICATION = 'absharProject.wsgi.application'
ASGI_APPLICATION = 'absharProject.asgi.application'
#
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = False
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'  # Use a consistent trailing slash for URL patterns
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Directory for additional static files (e.g., custom JS, CSS)
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Uploaded by users)
MEDIA_URL = '/media/'  # Use a consistent trailing slash
MEDIA_ROOT = BASE_DIR / 'uploads'  # Directory where uploaded files will be stored

CKEDITOR_UPLOAD_PATH = "uploads/articles/"  # همان فولدری که ساختی
CKEDITOR_IMAGE_BACKEND = "pillow"

CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'filebrowserUploadUrl': '/ckeditor/upload/',
        'filebrowserBrowseUrl': '/ckeditor/browse/',
        'contentsCss': ['/static/admin_panel/css/ckeditor_fa.css'],

        'height': 300,
        'width': 'auto',
        'extraPlugins': ','.join([
            'uploadimage',  # برای آپلود تصویر داخل متن
            'justify',  # برای Justify یا تنظیم چپ/راست
            'font',  # انتخاب فونت
            'colorbutton',  # رنگ متن
            'embed',  # Embed ویدیو
            'emoji',
            'autocomplete',  # وابسته به emoji
            'textmatch',  # وابسته به emoji

        ]),

        'font_names': 'Vazir;VazirB1;VazirB2;VazirB3;VazirB4;VazirBold;Tahoma;Arial;Sans-Serif;',
        'removePlugins': 'stylesheetparser,exportpdf,clipboard',
        'language': 'fa',
        'direction': 'rtl',
        'contentsLangDirection': 'rtl',
        'contentsLanguage': 'fa',
        'tabSpaces': 4,
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

Kavenegar_API = '795A7476367A46796858526E6E4744576A7A516E7750696E6C65654E654E525835784C38716437515270453D'

JALALI_DATE_DEFAULTS = {
    # if change it to true then all dates of the list_display will convert to the Jalali.
    'LIST_DISPLAY_AUTO_CONVERT': False,
    'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            'admin/js/django_jalali.min.js',
        ],
        'css': {
            'all': [
                'admin/css/django_jalali.min.css',
            ]
        }
    },
}

# Redis
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Timezone (خیلی مهم)
CELERY_ENABLE_UTC = True
CELERY_TIMEZONE = 'Asia/Tehran'

CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

SMS_PRICE = 219

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',  # مسیر فایل لاگ
            'encoding': 'utf-8',
        },
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {  # root logger
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}
SAMAN_TERMINAL_ID = "15758588"

SAMAN_REDIRECT_URL = (
    "https://rayacharge.ir/payment/callback/"
    # "http://localhost:8000/payment/callback/"
)

SAMAN_TOKEN_URL = (
    "https://sep.shaparak.ir/OnlinePG/OnlinePG"
)

SAMAN_VERIFY_URL = (
    "https://sep.shaparak.ir/verifyTxnRandomSessionkey/ipg/VerifyTransaction"
)
