# Generated by Django 5.2 on 2026-08-19 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_couponusage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
    ]
