# Generated by Django 5.2 on 2026-08-31 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_alter_couponusage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='smscredit',
            name='saman_ref_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مرجع سامان'),
        ),
        migrations.CreateModel(
            name='AnnouncementDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='images/announcement/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admin_panel.announcement')),
            ],
        ),
    ]
