# Generated by Django 5.2 on 2026-08-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_unifiedcharge_payment_pending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilinstallment',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
    ]
