# Generated by Django 5.2 on 2026-08-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_smscredit_saman_ref_num_announcementdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smscredit',
            name='saman_ref_num',
        ),
        migrations.AddField(
            model_name='smscredit',
            name='res_num',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='شناسه سفارش'),
        ),
    ]
