# Generated by Django 5.2 on 2026-09-03 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_remove_smscredit_saman_ref_num_smscredit_res_num'),
        ('user_app', '0011_alter_myhouse_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_count', models.PositiveIntegerField()),
                ('total_amount', models.PositiveIntegerField()),
                ('discount_amount', models.PositiveIntegerField(default=0)),
                ('final_amount', models.PositiveIntegerField()),
                ('res_num', models.CharField(db_index=True, max_length=100, unique=True)),
                ('ref_num', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20)),
                ('new_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_panel.coupon')),
                ('house', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to='user_app.myhouse')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admin_panel.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
