# Generated by Django 5.2 on 2026-09-25 11:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_subscriptionpayment'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_app', '0011_alter_myhouse_subdomain'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='smsmanagement',
            old_name='approved_at',
            new_name='reviewed_at',
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='smsmanagement',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='bankfund',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='civilinstallment',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
        migrations.AddField(
            model_name='expense',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='fund',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_read_statuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymoney',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='property',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='receivemoney',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='sewageinstallment',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='review_note',
            field=models.TextField(blank=True, verbose_name='دلیل نیاز به اصلاح'),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_sms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='smsmanagement',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('pending', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('revision', 'نیاز به اصلاح'), ('ready', 'آماده ارسال مجدد')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_pending',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید پرداخت'),
        ),
        migrations.AddField(
            model_name='unifiedcharge',
            name='payment_submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت درخواست پرداخت'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000000)], verbose_name='مبلغ تخفیف'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='doc_no',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='income',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='income',
            name='doc_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='income',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='paymoney',
            name='document_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='paymoney',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.unit'),
        ),
        migrations.AlterField(
            model_name='property',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.bank', verbose_name='شماره حساب'),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='doc_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='شماره سند'),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='receivemoney',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_app.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('message', 'recipient')},
        ),
        migrations.CreateModel(
            name='ChargeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='عنوان شارژ')),
                ('start_date', models.DateField(verbose_name='از تاریخ')),
                ('end_date', models.DateField(verbose_name='تا تاریخ')),
                ('unit_count', models.PositiveIntegerField(default=0, verbose_name='تعداد واحد')),
                ('other_cost_amount', models.PositiveIntegerField(default=0, verbose_name='هزینه متفرقه')),
                ('payment_deadline', models.DateField(blank=True, null=True, verbose_name='مهلت پرداخت')),
                ('payment_penalty_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ جریمه')),
                ('details', models.CharField(blank=True, max_length=4000, null=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('calculated', 'محاسبه شده'), ('finalized', 'نهایی شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='نهایی شده')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نهایی شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_charge_calculations', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_calculations', to='user_app.myhouse', verbose_name='ساختمان')),
            ],
            options={
                'verbose_name': 'محاسبه شارژ',
                'verbose_name_plural': 'محاسبات شارژ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargeCalculationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه هزینه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ هزینه')),
                ('title', models.CharField(max_length=1000, verbose_name='شرح هزینه')),
                ('source_date', models.DateField(blank=True, null=True, verbose_name='تاریخ هزینه')),
                ('allocation_basis', models.CharField(choices=[('equal', 'مساوی'), ('area', 'متراژ'), ('person', 'تعداد نفرات')], max_length=30, verbose_name='مبنای تقسیم')),
                ('allocation_scope', models.CharField(choices=[('all', 'همه واحدها'), ('occupied', 'واحدهای ساکن'), ('vacant', 'واحدهای خالی'), ('selected', 'انتخاب واحد')], default='all', max_length=20, verbose_name='واحدهای مشمول')),
                ('fixed_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ ثابت')),
                ('is_selected', models.BooleanField(default=True, verbose_name='انتخاب شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admin_panel.chargecalculation', verbose_name='محاسبه شارژ')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype', verbose_name='نوع هزینه')),
                ('selected_units', models.ManyToManyField(blank=True, related_name='selected_charge_calculation_items', to='user_app.unit', verbose_name='واحدهای انتخاب شده')),
                ('source_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charge_calculation_items', to='user_app.unit', verbose_name='واحد هزینه')),
            ],
            options={
                'verbose_name': 'هزینه انتخاب شده برای شارژ',
                'verbose_name_plural': 'هزینه های انتخاب شده برای شارژ',
                'ordering': ['source_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChargeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مقدار محاسباتی')),
                ('area_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='متراژ در زمان محاسبه')),
                ('people_snapshot', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد نفرات در زمان محاسبه')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='سهم واحد')),
                ('exact_amount', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='مبلغ دقیق محاسباتی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_allocations', to='user_app.unit', verbose_name='واحد')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='admin_panel.chargecalculationitem', verbose_name='هزینه محاسبه')),
            ],
            options={
                'verbose_name': 'سهم واحد از هزینه',
                'verbose_name_plural': 'سهم واحدها از هزینه',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialDocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='آخرین شماره سند')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_document_sequences', to='user_app.myhouse', verbose_name='ساختمان')),
            ],
        ),
        migrations.DeleteModel(
            name='ChargeByExpense',
        ),
        migrations.AddConstraint(
            model_name='chargecalculationitem',
            constraint=models.UniqueConstraint(fields=('calculation', 'content_type', 'object_id'), name='unique_charge_calculation_source'),
        ),
        migrations.AddConstraint(
            model_name='chargeallocation',
            constraint=models.UniqueConstraint(fields=('item', 'unit'), name='unique_charge_allocation_item_unit'),
        ),
        migrations.AddConstraint(
            model_name='financialdocumentsequence',
            constraint=models.UniqueConstraint(fields=('house',), name='unique_financial_document_sequence_per_house'),
        ),
    ]
