# Generated by Django 5.2 on 2026-06-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0010_alter_housepaymentgateway_gateway_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='subdomain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='زیردامنه'),
        ),
    ]
