# Generated by Django 5.2 on 2026-09-28 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_alter_myhouse_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='financial_document_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='شماره سند مالی'),
        ),
    ]
