# Generated by Django 5.2 on 2026-09-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_bank_financial_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhouse',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاریخ افتتاح'),
        ),
    ]
