# Generated by Django 5.2 on 2026-09-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0013_alter_myhouse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='create_at',
            field=models.DateTimeField(verbose_name='تاریخ افتتاح'),
        ),
        migrations.AlterField(
            model_name='myhouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
