# Generated by Django 5.2 on 2026-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_alter_bank_create_at_alter_myhouse_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='create_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ افتتاح حساب'),
        ),
    ]
