# Generated by Django 5.2 on 2026-10-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0003_alter_vote_unique_together_alter_vote_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='participant_type',
            field=models.CharField(choices=[('all', 'همه'), ('owners', 'مالکین'), ('renters', 'مستاجرین')], default='all', max_length=10),
        ),
    ]
