# Generated by Django 5.2 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls_app', '0004_poll_participant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='participant_type',
            field=models.CharField(choices=[('all', 'همه'), ('owners', 'فقط مالکین'), ('renters', 'فقط مستاجرین')], default='all', max_length=10),
        ),
    ]
